[workspace]
members = ["contracts/spore", "lib/types", "lib/utils", "contracts/cluster", "contracts/cluster_proxy", "contracts/cluster_agent", "contracts/spore_extension_lua"]
exclude = ["tests", "build"]

[profile.release]
overflow-checks = true
strip = true
opt-level = 's'
lto = false
codegen-units = 1
